apiVersion: v1
kind: Service
metadata:
  name: kured
  namespace: kube-system
  labels:
    app: kured
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: kured
  ports:
    - name: http
      port: 8080
